=== OlcorOlcor/DataFormats/HW3/3/xml/schemas/schema-5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:uni="http://www.our-example-data.org/university/xsd"
xmlns:jani="http://www.our-example-data.org/janitor/xsd"
xmlns:stud="http://www.our-example-data.org/student/xsd"
targetNamespace="http://www.our-example-data.org/dormitory/xsd" 
xmlns:xml="http://www.w3.org/XML/1998/namespace"
elementFormDefault="qualified">
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
<xs:import namespace="http://www.our-example-data.org/university/xsd" schemaLocation="schema-1.xsd"/>
<xs:import namespace="http://www.our-example-data.org/janitor/xsd" schemaLocation="schema-3.xsd"/>
<xs:import namespace="http://www.our-example-data.org/student/xsd" schemaLocation="schema-4.xsd"/>
    <xs:element name="Dormitory">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="address" type="xs:string"/>
                <xs:element name="Name">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute ref="xml:lang"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="hasBedBugs" type="xs:boolean"/>
                <xs:element ref="uni:University" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Janitors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="jani:Janitor" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DormRooms">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DormRoom" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Floor" type="xs:integer"/>
                                        <xs:element name="Number" type="xs:integer"/>
                                        <xs:element name="Capacity">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minExclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="HasToilet" type="xs:boolean"/>
                                        <xs:element name="Students">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="stud:Student" minOccurs="0" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OlcorOlcor/DataFormats/HW3/3/xml/data/data-6.xml
<?xml version="1.0" encoding="UTF-8"?>

<Dormitory xmlns="http://www.our-example-data.org/dormitory/xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.our-example-data.org/dormitory/xsd ../schemas/schema-5.xsd"
xmlns:jani="http://www.our-example-data.org/janitor/xsd"
xmlns:stud="http://www.our-example-data.org/student/xsd"
xmlns:uni="http://www.our-example-data.org/university/xsd">
    <address>Praha PÃ¡tkova 2136/3</address>
    <Name xml:lang="cs">17. Listopadu</Name>
    <hasBedBugs>false</hasBedBugs>
    <uni:University>
        <uni:id>2</uni:id>
        <uni:Name xml:lang="en">Charles University</uni:Name>
        <uni:webPage>https://cuni.cz</uni:webPage>
    </uni:University>
    <Janitors></Janitors>
    <DormRooms>
        <DormRoom>
            <Floor>100</Floor>
            <Number>1000</Number>
            <Capacity>3</Capacity>
            <HasToilet>true</HasToilet>
            <Students></Students>
        </DormRoom>
    </DormRooms>
</Dormitory>
